name: Node.js CI

on:
  push:
    branches: [ "feature/build_using_rs_package" ]
    
jobs:   
  build_swift:
    runs-on: macos-13
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '15'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lonelypaprika'

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          
      - uses: actions/checkout@v4
      - run: ls

      - name: Install dependencies
        run: cd next-swift && npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build swift
        run: cd next-swift && npm run build
      - run: ls
