name: Node.js CI

on:
  push:
    branches: [ "main-dev" ]
  pull_request:
    branches: [ "main-dev" ]

jobs:
  build_react_swift:
    runs-on: macos-13

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '15'
        
    - name: Download react-swift
      run: git clone https://github.com/LonelyPaprika/react-swift.git
    
    - name: Install Dependencies
      run: cd react-swift && npm install
    
    - name: Build react swift
      run: cd react-swift && npm run build

    - uses: actions/upload-artifact@v3
      with:
        path: react-swift/dist
        
  build_swift:
    runs-on: macos-13
    needs: build_react_swift
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '15'
          
      - uses: actions/checkout@v3
        with:
          path: swift
      - run: ls
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: react_swift/dist
      - run: ls
      - run: cd swift/swift && rm -rf out

      - name: Install dependencies
        run: cd swift/next-swift && npm install
    
      - name: Build swift
        run: cd swift/next-swift && npm run build
        
      - uses: actions/upload-artifact@v3
        with:
          path: swift/swift/out
      
    
    
